### ISSUE TITLE
Domoticz se nespustí

### ISSUE THREAD

**Issue by slimr** [trusnak/domoticz-turris#2]
root@turris:/usr/lib# domoticz status
domoticz: can't load library 'libudev.so.1'

Po automatickém upgradu na Turris os 3.7 znovunainstalován verze  domoticz_3.5878-3_mpc85xx.ipk
v systému je jen:
root@turris:/usr/lib# find / -name "libudev.so*"
/lib/libudev.so.0.12.0
/lib/libudev.so.0
/lib/libudev.so
tak vyřešeno nalinkováním
root@turris:/mnt/SD_CARD# ln -s /lib/libudev.so.0 /lib/libudev.so.1
Po tomto se rozběhl.
Po startu hlásí ještě, ale běží:
PluginSystem: Failed dynamic library load, install the latest libpython3.x library that is available for your platform.

**Comment by trusnak** [comment]
Prekompilovana nova verzia s aktualnymi kniznicami z TurrisOS 3.7.

New version, precompiled with TurrisOS 3.7 libraries.
