### ISSUE TITLE
Nastaveni hardwaru se nezobrazí

### ISSUE THREAD

**Issue by slimr** [trusnak/domoticz-turris#3]
Na řádku 4697 v www/app/HardwareController.js je jedna závorka navíc

**Comment by trusnak** [comment]
V balicku je to v poriadku ale vyzera ze cely adresar www instalator neaktualizuje.

**Comment by trusnak** [comment]
Solved in: https://github.com/trusnak/domoticz-turris/commit/5c7a5d29c8e7324b87435b5933dc058545535b8c
